# Generated by Django 4.2.8 on 2023-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Brand", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
            ],
        ),
    ]
